# Generated by Django 3.1.4 on 2020-12-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=72, verbose_name='Название')),
                ('note', models.TextField(verbose_name='Описание')),
                ('coordinates', models.CharField(max_length=72, verbose_name='Координаты')),
                ('person', models.CharField(max_length=72, verbose_name='Автор')),
            ],
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
